sim:
  gal_type: exp
  psf_type: gauss
  shear_scene: True
  n_coadd: 5
  scale: 0.263
  wcs_kws:
    position_angle_range: [0, 0]
    scale_frac_std: 0.0
    shear_std: 0.0
    dither_range: [-0.5, 0.5]

run:
  n_patches: 1000000
